name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  MONGO_URI: ${{secrets.MONGO_URI}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install backend dependencies
        run: pip install -r ./requirements.txt
      - name: Show env
        run: env
      - name: Print mongouri
        run: python3 show_env.py
      - name: Run pylint
        run: pylint src --rcfile=.pylintrc
      - name: run pytest
        run: coverage run --branch -m pytest
        env:
          MONGO_URI: ${{secrets.MONGO_URI}}
      - name: Coverage report
        run: coverage xml
